### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by JRyuzaki** [RChaubey16/Blogging-Website#14]
Careful this is a sql injection vulnerability https://github.com/RChaubey16/Blogging-Website/blob/768e71457e735836bea1af10e1f58a1235441eee/like.php#L14

I would suggest you to replace all queries with prepared statements as this would mitigate the vulnerability :D
https://www.w3schools.com/php/php_mysql_prepared_statements.asp

**Comment by RChaubey16** [comment]
Done.
