### ISSUE TITLE
URL Not Found

### ISSUE THREAD

**Issue by Libbna** [RChaubey16/Blogging-Website#35]
![image](https://user-images.githubusercontent.com/46792570/132120235-96fec3b7-e21d-465b-991a-9fb20aae13ad.png)
Not able to figure out the right URL path.

**Comment by RChaubey16** [comment]
Everything seems perfect. The error must be on your side.

**Comment by Libbna** [comment]
Issue resolved. The issue was on my site, I was entering the wrong URL path.
