### ISSUE TITLE
CSS is not loading on the website

### ISSUE THREAD

**Issue by Libbna** [RChaubey16/Blogging-Website#54]
![image](https://user-images.githubusercontent.com/46792570/134514061-c3089a99-dfea-4850-86f5-f51fca160ba7.png)
After running the website I'm getting this result.

**Comment by RChaubey16** [comment]
In partials/header.php, of your forked repo, change the base tag's href attribute to the domain you are using to run the project.
Example: <base href ="http://localhost/BlogIt/" /> to <base href ="http://localhost:8000/" />.
something like this.

If the problem still persists, do let me know.
