### ISSUE TITLE
Error during sql file import.

### ISSUE THREAD

**Issue by JayKandari** [RChaubey16/Blogging-Website#7]
![image](https://user-images.githubusercontent.com/1266231/130560324-67963fdc-cfc3-47fd-8f4b-09e6bdf8339b.png)
No tables are getting imported.

**Comment by JayKandari** [comment]
I was able to bypass this issue by removing the `COLLATE=utf8mb4_0900_ai_ci` item from the `blogsite.sql` file.

**Comment by RChaubey16** [comment]
Issue resolved.

**Comment by RChaubey16** [comment]
Issue resolved.
