### ISSUE TITLE
When logged in, user is not able to view the homepage correctly.

### ISSUE THREAD

**Issue by JayKandari** [RChaubey16/Blogging-Website#8]
![image](https://user-images.githubusercontent.com/1266231/130560879-bc37b225-1180-4184-bca4-2fd1f4ee6778.png)

The banner is missing by default, We only see banner if we click the "slider" button on top-right side.

**Comment by RChaubey16** [comment]
The authenticated user has access to the dynamic banner feature whereas the visitor of the site i.e. a not registered user will only have access to the hard-coded banner on home page and not the dynamic one.
